version: 2

jobs:
  deploy:
    docker:
      - image: circleci/ruby:2.4.1-node-browsers

    steps:
      - checkout

      - run:
          name: Deploy
          command: bash ./deploy/deploy_production.sh

      - save_cache:
          key: v1-package-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/

workflows:
  version: 2
  build:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - master